export default {
    siteTitle: "The Storyteller",
    siteSubTitle: "Minimal musings on code, design, and life",
    copyright: "© 2025 The Storyteller. All Rights Reserved.",
    showAuthorsOnHomePage: false,
    showFeaturrdPostsOnHomePage: true,
    labels: {
        featuredPosts: "Featured Posts",
        latestPosts: "Latest Posts",
        viewAllPosts: "View All Posts",
        backToHome: "Back to Home",
        youMightAlsoLike: "You Might Also Like",
        postedIn: "Posted in",
        noArticlesFound: "No articles found.",
        allCategories: "All Categories",
        allTags: "All Tags",
        exploreArticlesByTags:"Explore articles organized by topics",
        exploreArticlesByCategories:"Explore articles organized by topics",
    },
    showCategoriesLinkOnFooter: true,
    showTagsLinkOnFooter: true,
    showSimilarPosts: true,
    showReadMoreLinkOnFeaturedPosts: true,
    showThumbnailOnFeaturedPosts: true,
    numberOfLatestPostsPerPage: 6,
}

